/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bakery.h"

bool_t
xdr_Ticket (XDR *xdrs, Ticket *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->number))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ServiceRequest (XDR *xdrs, ServiceRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ticket_number))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ServiceResponse (XDR *xdrs, ServiceResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}
