/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN
#define NOT_YOUR_QUEUE 4294967295

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define GET_TICKET 1
#define GET_SERVICE 2

struct Ticket {
	int number;
};
typedef struct Ticket Ticket;

struct ServiceRequest {
	int ticket_number;
};
typedef struct ServiceRequest ServiceRequest;

struct ServiceResponse {
	long result;
};
typedef struct ServiceResponse ServiceResponse;

#define BAKERY_PROG 0x20000002
#define BAKERY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_TICKET 1
extern  enum clnt_stat get_ticket_1(void *, struct Ticket *, CLIENT *);
extern  bool_t get_ticket_1_svc(void *, struct Ticket *, struct svc_req *);
#define GET_SERVICE 2
extern  enum clnt_stat get_service_1(struct ServiceRequest *, struct ServiceResponse *, CLIENT *);
extern  bool_t get_service_1_svc(struct ServiceRequest *, struct ServiceResponse *, struct svc_req *);
extern int bakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_TICKET 1
extern  enum clnt_stat get_ticket_1();
extern  bool_t get_ticket_1_svc();
#define GET_SERVICE 2
extern  enum clnt_stat get_service_1();
extern  bool_t get_service_1_svc();
extern int bakery_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Ticket (XDR *, Ticket*);
extern  bool_t xdr_ServiceRequest (XDR *, ServiceRequest*);
extern  bool_t xdr_ServiceResponse (XDR *, ServiceResponse*);

#else /* K&R C */
extern bool_t xdr_Ticket ();
extern bool_t xdr_ServiceRequest ();
extern bool_t xdr_ServiceResponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
