/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "bakery.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
get_ticket_1(void *argp, struct Ticket *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, GET_TICKET,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_Ticket, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_service_1(struct ServiceRequest *argp, struct ServiceResponse *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, GET_SERVICE,
		(xdrproc_t) xdr_ServiceRequest, (caddr_t) argp,
		(xdrproc_t) xdr_ServiceResponse, (caddr_t) clnt_res,
		TIMEOUT));
}
