/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <stdint.h>
#include <time.h>
#include <unistd.h>
#include <linux/time.h>

#define MAX_CLIENTS 10000

int choosing[MAX_CLIENTS] = {0};
int numbers[MAX_CLIENTS] = {0};
int pids[MAX_CLIENTS] = {0};

int* get_number_1_svc(int* argp, struct svc_req* rqstp)
{
    static int result = 0;
    int ind = *argp % MAX_CLIENTS;
    int number = numbers[0];
    pids[ind] = *argp;

    choosing[ind] = 1;
    for (int i = 0; i < MAX_CLIENTS; i++)
    {
        if (numbers[i] > number)
        {
            number = numbers[i];
        }
    }
    numbers[ind] = number + 1;
    result = result + 1;
    choosing[ind] = 0;

    return &result;
}

long* bakery_proc_1_svc(struct REQUEST* argp, struct svc_req* rqstp)
{
    static long result;
    int i = argp->ticket % MAX_CLIENTS;


    struct timespec ts;
    clock_gettime(CLOCK_REALTIME, &ts);
    result = (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
    numbers[i] = 0;

    return &result;
}
