/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>


int flag = 1;
void sig_handler(int sig_num)
{
    flag = 0;
}

void bakery_prog_1(char* host)
{
    CLIENT* clnt;
    int* number;
    int get_number_1_arg;
    long* time;
    struct REQUEST bakery_proc_1_arg;

#ifndef DEBUG
    clnt = clnt_create(host, BAKERY_PROG, BAKERY_VER, "udp");
    if (clnt == NULL)
    {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */
    get_number_1_arg = getpid();

    while (flag)
    {
#ifdef SHOW
        number = get_number_1(&get_number_1_arg, clnt);
#else
        while ((number = get_number_1(&get_number_1_arg, clnt)) == (int*)(-1))
            ;
#endif //SHOW
        if (number == (int*)NULL)
        {
            clnt_perror(clnt, "call failed");
        }

#ifdef SHOW
        // ей говорим, что здесь он будет ждать своей очереди
        time = bakery_proc_1(&bakery_proc_1_arg, clnt);
#else
        // если сервер занят, то он выкидывает -1
        while ((time = bakery_proc_1(&bakery_proc_1_arg, clnt)) == (long*)(-1))
            ;
#endif //SHOW
        if (time == (long*)NULL)
        {
            clnt_perror(clnt, "call failed");
        }
        printf("%d %ld\n", *number, *time);
        usleep(1 * 10000);
    }

#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
}


int main(int argc, char* argv[])
{
    char* host;

    if (argc < 2)
    {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }
    if (signal(SIGINT, sig_handler) == SIG_ERR)
    {
        perror("signal");
        exit(1);
    }
    host = argv[1];
    bakery_prog_1(host);
    exit(0);
}
