/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_CLIENTS 5000

#define BAKERY_PROG 0x20000001
#define BAKERY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define REGISTER_PROC 1
extern  int * register_proc_1(int *, CLIENT *);
extern  int * register_proc_1_svc(int *, struct svc_req *);
#define RESULT_PROC 2
extern  long * result_proc_1(int *, CLIENT *);
extern  long * result_proc_1_svc(int *, struct svc_req *);
extern int bakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REGISTER_PROC 1
extern  int * register_proc_1();
extern  int * register_proc_1_svc();
#define RESULT_PROC 2
extern  long * result_proc_1();
extern  long * result_proc_1_svc();
extern int bakery_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
