/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bakery.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

struct thread_data_t
{
	struct svc_req *rqstp;
	SVCXPRT *transp;
	argument_t argument;
	xdrproc_t xdr_argument;
	xdrproc_t xdr_result;
	char *(*local)(char *, struct svc_req *);
};
typedef struct thread_data_t thread_data_t;
pthread_attr_t attr;
pthread_t thread;

static void *
bakery_prog_worker(void *data_ptr) {
	thread_data_t *thread_data_ptr = (thread_data_t *)data_ptr;
	struct svc_req *rqstp = thread_data_ptr->rqstp;
	register SVCXPRT *transp = thread_data_ptr->transp;
	xdrproc_t _xdr_argument = thread_data_ptr->xdr_argument;
	xdrproc_t _xdr_result = thread_data_ptr->xdr_result;
	char *(*local)(char *, struct svc_req *) = thread_data_ptr->local;
	char *result;

	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}

	free(data_ptr);
	return NULL;
}

static void
bakery_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		struct REQUEST get_number_1_arg;
		struct REQUEST bakery_service_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GET_NUMBER:
		_xdr_argument = (xdrproc_t) xdr_REQUEST;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) get_number_1_svc;
		break;

	case BAKERY_SERVICE:
		_xdr_argument = (xdrproc_t) xdr_REQUEST;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) bakery_service_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	if (rqstp->rq_proc == GET_NUMBER) {
		thread_data_t *thread_data_ptr = (thread_data_t *)malloc(sizeof(thread_data_t));
		if (thread_data_ptr == NULL)
		{
			perror("malloc");
			exit(1);
		}
		thread_data_ptr->rqstp = rqstp;
		thread_data_ptr->transp = transp;
		thread_data_ptr->local = local;
		thread_data_ptr->argument = argument;
		thread_data_ptr->xdr_argument = _xdr_argument;
		thread_data_ptr->xdr_result = _xdr_result;

		memset ((char *)&argument, 0, sizeof (argument));
		if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
			svcerr_decode (transp);
			return;
		}

		pthread_attr_init(&attr);
		if (pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED) == -1)
		{
			perror("pthread_attr_setdetachstate");
			svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &thread_data_ptr->argument);
			free(thread_data_ptr);
			exit(1);
		}
		
		if (pthread_create(&thread, &attr, bakery_prog_worker, (void *)thread_data_ptr) == -1)
		{
			perror("pthread_create");
			svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &thread_data_ptr->argument);
			free(thread_data_ptr);
			exit(1);
		}
		return;
	} else if (rqstp->rq_proc == BAKERY_SERVICE) {
		result = (*local)((char *)&argument, rqstp);
		if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
			svcerr_systemerr (transp);
		}
		if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
			fprintf (stderr, "%s", "unable to free arguments");
			exit (1);
		}
		return;
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (BAKERY_PROG, BAKERY_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, BAKERY_PROG, BAKERY_VER, bakery_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (BAKERY_PROG, BAKERY_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, BAKERY_PROG, BAKERY_VER, bakery_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (BAKERY_PROG, BAKERY_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
