/*
* This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <stdio.h>
#include <unistd.h>
#include <time.h>
#include <pthread.h>

int numbers[MAX_CLIENTS];
static int current_ticket = 0;
static pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;

int *
register_proc_1_svc(int *argp, struct svc_req *rqstp)
{
  int result;
  int idx = *argp % MAX_CLIENTS;

  pthread_mutex_lock(&mutex);

  current_ticket++;
  result = current_ticket;
  numbers[idx] = result;

  pthread_mutex_unlock(&mutex);
  
  return &result;
}

long *
result_proc_1_svc(int *argp, struct svc_req *rqstp)
{
  setbuf(stdout, NULL);

  static long  result;
  int j = *argp;
  struct timespec end;

  int ticket = numbers[j];

  for (int i = 0; i < MAX_CLIENTS; ++i)
  {
    while ((numbers[i] != 0) && ((numbers[i] < numbers[j]) || (numbers[i] == numbers[j]) && (i < j)));
  }

  clock_gettime(CLOCK_MONOTONIC, &end);
  result = end.tv_nsec;

  numbers[j] = 0;

  return &result;
}