/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>

int flag = 1;
void sig_handler(int sig_num)
{
    flag = 0;
}

void
bakery_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  register_proc_1_arg;
	long  *result_2;
	int  result_proc_1_arg;


	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	while (flag)
	{
		register_proc_1_arg = getpid();
		result_1 = register_proc_1(&register_proc_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		result_proc_1_arg = getpid() % 5000;
		result_2 = result_proc_1(&result_proc_1_arg, clnt);
		if (result_2 == (long *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		printf("%d, %ld\n", *result_1, *result_2);
    }

	clnt_destroy (clnt);
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	if (signal(SIGINT, sig_handler) == SIG_ERR)
    {
        perror("signal");
        exit(1);
    }
	host = argv[1];
	bakery_prog_1 (host);
	exit (0);
}
